create table tb_bank (id  bigserial not null, account_number varchar(255), account_type_label varchar(255), label varchar(255), primary key (id));
create table tb_client (id  bigserial not null, cpf varchar(255), name varchar(255), phone varchar(255), bank_id int8, primary key (id));
create table tb_installment (id  bigserial not null, comission float8, full_value float8, installment_interest float8, installment_number float8, installment_value float8, primary key (id));
create table tb_rate_installment (rate_table_id int8 not null, installment_id int8 not null, primary key (rate_table_id, installment_id));
create table tb_rate_table (id  bigserial not null, name varchar(255), primary key (id));
create table tb_solicitation (id  bigserial not null, card_number varchar(255), client_id int8, comission float8, comission_value float8, desired_value float8, installment_id int8, installment_interest float8, installment_interest_value float8, installment_value float8, rate_table_id int8, total_loan float8, primary key (id));
alter table if exists tb_client add constraint FKmrx7kvykkkr8bnsqs03b2eqhr foreign key (bank_id) references tb_bank;
alter table if exists tb_rate_installment add constraint FKmxv8bwe6imwx50tasqb2h0xlq foreign key (installment_id) references tb_installment;
alter table if exists tb_rate_installment add constraint FKmo851csylqvo4vy8v3uta0y1y foreign key (rate_table_id) references tb_rate_table;
create table tb_bank (id  bigserial not null, account_number varchar(255), account_type_label varchar(255), label varchar(255), primary key (id));
create table tb_client (id  bigserial not null, cpf varchar(255), name varchar(255), phone varchar(255), bank_id int8, primary key (id));
create table tb_installment (id  bigserial not null, comission float8, full_value float8, installment_interest float8, installment_number float8, installment_value float8, primary key (id));
create table tb_rate_installment (rate_table_id int8 not null, installment_id int8 not null, primary key (rate_table_id, installment_id));
create table tb_rate_table (id  bigserial not null, name varchar(255), primary key (id));
create table tb_solicitation (id  bigserial not null, card_number varchar(255), client_id int8, comission float8, comission_value float8, desired_value float8, installment_id int8, installment_interest float8, installment_interest_value float8, installment_value float8, rate_table_id int8, total_loan float8, primary key (id));
alter table if exists tb_client add constraint FKmrx7kvykkkr8bnsqs03b2eqhr foreign key (bank_id) references tb_bank;
alter table if exists tb_rate_installment add constraint FKmxv8bwe6imwx50tasqb2h0xlq foreign key (installment_id) references tb_installment;
alter table if exists tb_rate_installment add constraint FKmo851csylqvo4vy8v3uta0y1y foreign key (rate_table_id) references tb_rate_table;
create table tb_bank (id  bigserial not null, account_number varchar(255), account_type_label varchar(255), label varchar(255), primary key (id));
create table tb_client (id  bigserial not null, cpf varchar(255), name varchar(255), phone varchar(255), bank_id int8, primary key (id));
create table tb_installment (id  bigserial not null, comission float8, full_value float8, installment_interest float8, installment_number float8, installment_value float8, primary key (id));
create table tb_rate_installment (rate_table_id int8 not null, installment_id int8 not null, primary key (rate_table_id, installment_id));
create table tb_rate_table (id  bigserial not null, name varchar(255), primary key (id));
create table tb_solicitation (id  bigserial not null, card_number varchar(255), client_id int8, comission float8, comission_value float8, desired_value float8, installment_id int8, installment_interest float8, installment_interest_value float8, installment_value float8, rate_table_id int8, total_loan float8, primary key (id));
alter table if exists tb_client add constraint FKmrx7kvykkkr8bnsqs03b2eqhr foreign key (bank_id) references tb_bank;
alter table if exists tb_rate_installment add constraint FKmxv8bwe6imwx50tasqb2h0xlq foreign key (installment_id) references tb_installment;
alter table if exists tb_rate_installment add constraint FKmo851csylqvo4vy8v3uta0y1y foreign key (rate_table_id) references tb_rate_table;
create table tb_bank (id  bigserial not null, account_number varchar(255), account_type_label varchar(255), label varchar(255), primary key (id));
create table tb_client (id  bigserial not null, cpf varchar(255), name varchar(255), phone varchar(255), bank_id int8, primary key (id));
create table tb_installment (id  bigserial not null, comission float8, full_value float8, installment_interest float8, installment_number float8, installment_value float8, primary key (id));
create table tb_rate_installment (rate_table_id int8 not null, installment_id int8 not null, primary key (rate_table_id, installment_id));
create table tb_rate_table (id  bigserial not null, name varchar(255), primary key (id));
create table tb_solicitation (id  bigserial not null, card_number varchar(255), client_id int8, comission float8, comission_value float8, desired_value float8, installment_id int8, installment_interest float8, installment_interest_value float8, installment_value float8, rate_table_id int8, total_loan float8, primary key (id));
alter table if exists tb_client add constraint FKmrx7kvykkkr8bnsqs03b2eqhr foreign key (bank_id) references tb_bank;
alter table if exists tb_rate_installment add constraint FKmxv8bwe6imwx50tasqb2h0xlq foreign key (installment_id) references tb_installment;
alter table if exists tb_rate_installment add constraint FKmo851csylqvo4vy8v3uta0y1y foreign key (rate_table_id) references tb_rate_table;
